spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:6432/owndb
    username: ownuser
    password: ownpassword

ownapp:
  baseUrl: http://ownpage.local:8066

owner:
  setup-password: this-is-a-complex-setup-password!
