server:
  port: 8456
  servlet:
    context-path: /api
spring:
  main.banner-mode: off
  output.ansi.enabled: ALWAYS

ownapp:
  baseUrl: http://localhost:8456
  oauth2:
    client_id: change-me-client-id
    guest_client_id: guest-client-id

jwt:
  public_key: classpath:ownpage.rsa.pub.pem.pkcs8
  private_key: classpath:ownpage.rsa
